### ISSUE TITLE
It just doesn't launch

### ISSUE THREAD

**Issue by FrogsForLife** [YaLTeR/bxt-launcher#4]
When trying to open through konsole, I get "error while loading shared libraries: libgtop-2.0.so.11: cannot open shared object file: No such file or directory"

I'm running Manjaro Linux 

I tried looking up " libgtop-2.0.so.11" on AUR, and I couldn't find anything.

**Comment by YaLTeR** [comment]
Seems like you need https://archlinux.org/packages/extra/x86_64/libgtop/ from the regular Arch repo.
