### ISSUE TITLE
The launcher isnt launching half life.

### ISSUE THREAD

**Issue by boofiboi** [YaLTeR/bxt-launcher#5]
The launcher launched half life for the first time, but half life doesnt have any launch options set, and launching the game again does nothing.

https://user-images.githubusercontent.com/79476279/173201341-0636d268-96f5-4b1b-b15e-7371110de8de.mp4

**Comment by YaLTeR** [comment]
Hmm. I haven't used the launcher in a while (need to get around to rewriting and updating it to add Flatpak and bxt-rs support) so maybe @chinese-soup could help you out?

**Comment by boofiboi** [comment]
Maybe it has something to do with my Half-Life install being on a separate partition?

**Comment by boofiboi** [comment]
Nope. It doesn't matter if its on a separate BTRFS partition, still doesn't launch.

**Comment by boofiboi** [comment]
Using 0.1 works.

I have no idea why, but it does.
